apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-backend-api
  labels:
    app: shop-backend
spec:
  replicas: 3  # Minimum of three Pod replicas
  selector:
    matchLabels:
      app: shop-backend
  template:
    metadata:
      labels:
        app: shop-backend
    spec:
      containers:
      - name: shop-backend-container
        image: strm/helloworld-http:latest  # Container image
        ports:
        - containerPort: 80  # Container exposes port 80

        # LivenessProbe configuration
        livenessProbe:
          tcpSocket:
            port: 80  # Makes TCP requests to port 80
          initialDelaySeconds: 10  # Initial probe delay of 10 seconds
          periodSeconds: 10  # Check every 10 seconds (default)

        # ReadinessProbe configuration
        readinessProbe:
          httpGet:
            path: /
            port: 80  # HTTP requests to "/" endpoint on port 80
          initialDelaySeconds: 10  # Initial probe delay of 10 seconds
          periodSeconds: 1  # Check every second
          failureThreshold: 2  # Maximum of 2 probe failures before marking the container as "not ready"
